# Generated by Django 2.1.7 on 2020-09-28 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundLobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment_PO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Shipment POs',
                'verbose_name_plural': 'Shipment POs',
            },
        ),
        migrations.RenameField(
            model_name='receive_shipment_item',
            old_name='date_received',
            new_name='date_validated',
        ),
        migrations.RemoveField(
            model_name='receive_shipment_item',
            name='awl_bl',
        ),
        migrations.RemoveField(
            model_name='receive_shipment_item',
            name='container_num',
        ),
        migrations.RemoveField(
            model_name='receive_shipment_item',
            name='container_type',
        ),
        migrations.RemoveField(
            model_name='receive_shipment_item',
            name='dr_num',
        ),
        migrations.RemoveField(
            model_name='receive_shipment_item',
            name='invoice_num',
        ),
        migrations.RemoveField(
            model_name='receive_shipment_item',
            name='rr_num',
        ),
        migrations.RemoveField(
            model_name='receive_shipment_item',
            name='ship_category',
        ),
        migrations.RemoveField(
            model_name='receive_shipment_item',
            name='ship_trucking',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='po_num',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='supplier',
        ),
        migrations.AddField(
            model_name='purchase_order',
            name='supplier',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='awl_bl',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='container_num',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='container_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='date_dr',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='date_warehouse',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dr_num',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='invoice_num',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='rr_num',
            field=models.CharField(blank=True, default=' ', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ship_category',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='ship_trucking',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipment_po',
            name='po_num',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Purchase_Order'),
        ),
        migrations.AddField(
            model_name='shipment_po',
            name='shipment_num',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Shipment'),
        ),
        migrations.AddField(
            model_name='inboundlobby',
            name='shipment_num',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Shipment'),
        ),
    ]
