# Generated by Django 2.1.7 on 2020-09-28 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0002_auto_20200928_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receive_shipment_item',
            name='shipment_num',
        ),
        migrations.RemoveField(
            model_name='shipment_summary',
            name='shipment_num',
        ),
        migrations.AddField(
            model_name='receive_shipment_item',
            name='shipment_po',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Shipment_PO'),
        ),
        migrations.AddField(
            model_name='shipment_summary',
            name='shipment_po',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Shipment_PO'),
        ),
    ]
