# Generated by Django 2.1.7 on 2020-10-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0003_auto_20201012_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='wo_assembly',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wo_assembly',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='wo_assembly/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='wo_assembly',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wo_coupling',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wo_coupling',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='wo_coupling/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='wo_coupling',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wo_finished',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wo_finished',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='wo_finished/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='wo_finished',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wo_issuance_list',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wo_issuance_list',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='wo_issuance/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='wo_issuance_list',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wo_testing',
            name='height_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='wo_testing',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='wo_testing/', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='wo_testing',
            name='width_field',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
