# Generated by Django 2.1.7 on 2020-09-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0003_auto_20200928_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='put_away_summary',
            name='status',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
