# Generated by Django 2.1.7 on 2020-10-16 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0004_auto_20201015_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfmr_item',
            name='report_num',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.DFMR_Report'),
        ),
    ]
