# Generated by Django 2.1.7 on 2020-09-29 08:56

from django.db import migrations, models
import invsys.models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0004_auto_20200929_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='imgpath',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imgpath',
        ),
        migrations.AddField(
            model_name='item',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=invsys.models.upload_item_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='item',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=invsys.models.upload_prod_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='product',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=invsys.models.upload_whse_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
