# Generated by Django 2.1.7 on 2020-10-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0005_auto_20201016_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
