# Generated by Django 2.1.7 on 2020-10-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0006_auto_20201025_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='wo_production_schedule',
            name='issues',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
