# Generated by Django 2.1.7 on 2020-10-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0007_wo_production_schedule_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
