# Generated by Django 2.1.7 on 2020-11-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0008_auto_20201028_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_order',
            name='finished_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
