# Generated by Django 2.1.7 on 2020-09-29 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0008_auto_20200929_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to='item/', validators=[django.core.validators.FileExtensionValidator(['jpg'])], width_field='width_field'),
        ),
    ]
