# Generated by Django 2.1.7 on 2020-11-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0009_auto_20201106_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='column',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='direction',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='layer',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='rack',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
