# Generated by Django 2.1.7 on 2020-09-29 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0010_auto_20200929_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='image',
        ),
    ]
