# Generated by Django 2.1.7 on 2020-11-10 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0011_auto_20201110_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packing_Finish_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default='', max_length=200)),
                ('transaction_type', models.CharField(default='', max_length=200)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_location', models.CharField(default='', max_length=200)),
                ('prod_quantity', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user_department', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('prod_number', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Product')),
            ],
            options={
                'verbose_name': 'Finished Packing Transaction',
                'verbose_name_plural': 'Finished Packing Transactions',
            },
        ),
        migrations.CreateModel(
            name='Packing_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.IntegerField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('picked', models.BooleanField(default=False)),
                ('bin_location', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='invsys.Warehouse')),
                ('prod_num', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Product')),
            ],
            options={
                'verbose_name': 'Packing Product',
                'verbose_name_plural': 'Packing Products',
            },
        ),
        migrations.CreateModel(
            name='Packing_Schedule',
            fields=[
                ('schedule_num', models.AutoField(primary_key=True, serialize=False)),
                ('date_scheduled', models.DateField()),
                ('notes', models.CharField(default='', max_length=200)),
                ('cleared', models.BooleanField(default=False)),
                ('issues', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Packing Schedule',
                'verbose_name_plural': 'Packing Schedules',
            },
        ),
        migrations.CreateModel(
            name='Packing_Schedule_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default='', max_length=200)),
                ('transaction_type', models.CharField(default='', max_length=200)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_location', models.CharField(default='', max_length=200)),
                ('prod_quantity', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('user_department', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('prod_number', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Product')),
            ],
            options={
                'verbose_name': 'Packing Schedule Transaction',
                'verbose_name_plural': 'Packing Schedule Transactions',
            },
        ),
        migrations.CreateModel(
            name='Packing_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_quantity', models.IntegerField(blank=True, null=True)),
                ('picked_quantity', models.IntegerField(blank=True, null=True)),
                ('discrepancy', models.BooleanField(default=False)),
                ('discrepancy_quantity', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date_scheduled', models.DateField()),
                ('date_picked', models.DateField()),
                ('reference_number', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('bin_location', models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='invsys.Warehouse')),
                ('prod_num', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Product')),
                ('schedule_num', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Packing_Schedule')),
                ('wo_num', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Work_Order')),
            ],
            options={
                'verbose_name': 'Packing Summary',
                'verbose_name_plural': 'Packing Summaries',
            },
        ),
        migrations.AddField(
            model_name='packing_product',
            name='schedule_num',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Packing_Schedule'),
        ),
        migrations.AddField(
            model_name='packing_product',
            name='wo_num',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Work_Order'),
        ),
    ]
