# Generated by Django 2.1.7 on 2020-09-30 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0012_auto_20200929_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer_Add_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default='', max_length=200)),
                ('transaction_type', models.CharField(default='', max_length=200)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_location', models.CharField(default='', max_length=200)),
                ('item_quantity', models.IntegerField(blank=True, null=True)),
                ('item_number', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Item')),
            ],
            options={
                'verbose_name': 'Transfer Add Transaction',
                'verbose_name_plural': 'Transfer Add Transactions',
            },
        ),
        migrations.CreateModel(
            name='Transfer_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.IntegerField(blank=True, null=True)),
                ('total_cost', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(default='', max_length=200)),
                ('bin_location', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Warehouse')),
                ('iaf_operator', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.IAF_operator')),
                ('item_number', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Item')),
            ],
            options={
                'verbose_name': 'Transfer Item',
                'verbose_name_plural': 'Transfer Items',
            },
        ),
        migrations.CreateModel(
            name='Transfer_Report',
            fields=[
                ('report_num', models.AutoField(primary_key=True, serialize=False)),
                ('date_reported', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(default='', max_length=200)),
                ('iaf_whse', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.IAF_whse')),
            ],
            options={
                'verbose_name': 'Transfer Report',
                'verbose_name_plural': 'Transfer Reports',
            },
        ),
        migrations.CreateModel(
            name='Transfer_Subt_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default='', max_length=200)),
                ('transaction_type', models.CharField(default='', max_length=200)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_location', models.CharField(default='', max_length=200)),
                ('item_quantity', models.IntegerField(blank=True, null=True)),
                ('item_number', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Item')),
            ],
            options={
                'verbose_name': 'Transfer Subt Transaction',
                'verbose_name_plural': 'Transfer Subt Transactions',
            },
        ),
        migrations.AddField(
            model_name='transfer_item',
            name='report_num',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Transfer_Report'),
        ),
    ]
