# Generated by Django 2.1.7 on 2020-11-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0012_auto_20201111_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iaf_report',
            name='date_requested',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
