# Generated by Django 2.1.7 on 2020-09-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0013_auto_20200930_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dfmr_item',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dfmr_report',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dismantle_report',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dmmr_report',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sa_report',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer_item',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer_report',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
