# Generated by Django 2.1.7 on 2020-09-30 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0015_auto_20200930_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_lobby',
            name='prod_sched',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.WO_Production_Schedule'),
        ),
    ]
