# Generated by Django 2.1.7 on 2020-09-30 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0016_shipping_lobby_prod_sched'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_lobby',
            name='reference_number',
        ),
    ]
