# Generated by Django 2.1.7 on 2020-09-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0018_auto_20200930_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recproduct_item_transaction',
            old_name='prod_number',
            new_name='item_number',
        ),
        migrations.RenameField(
            model_name='recproduct_item_transaction',
            old_name='prod_quantity',
            new_name='item_quantity',
        ),
    ]
