# Generated by Django 2.1.7 on 2020-09-30 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0019_auto_20200930_1818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping_outbound',
            options={'verbose_name': 'Shipping Outbound', 'verbose_name_plural': 'Shipping Outbounds'},
        ),
        migrations.RenameField(
            model_name='shipping_outbound',
            old_name='date_received',
            new_name='date_out',
        ),
        migrations.RenameField(
            model_name='shipping_outbound',
            old_name='notes',
            new_name='ship_out_num',
        ),
        migrations.RemoveField(
            model_name='shipping_outbound',
            name='checked_by',
        ),
        migrations.RemoveField(
            model_name='shipping_outbound',
            name='prod_number',
        ),
        migrations.RemoveField(
            model_name='shipping_outbound',
            name='prod_sched',
        ),
        migrations.RemoveField(
            model_name='shipping_outbound',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='shipping_outbound',
            name='received_by',
        ),
        migrations.AddField(
            model_name='shipping_outbound',
            name='wo_num',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Work_Order'),
        ),
    ]
