# Generated by Django 2.1.7 on 2020-09-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0020_auto_20200930_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_outbound',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
