# Generated by Django 2.1.7 on 2020-09-30 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0021_shipping_outbound_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_outbound',
            name='date_out',
            field=models.DateField(blank=True, null=True),
        ),
    ]
