# Generated by Django 2.1.7 on 2020-09-30 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0022_auto_20201001_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_outbound_transaction',
            name='prod_number',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Product'),
        ),
        migrations.AlterField(
            model_name='shipping_whseproduct_transaction',
            name='prod_number',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Product'),
        ),
    ]
