# Generated by Django 2.1.7 on 2020-10-01 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invsys', '0023_auto_20201001_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolvePO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_resolved', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('po_num', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Purchase_Order')),
            ],
            options={
                'verbose_name': 'Resolve PO',
                'verbose_name_plural': 'Resolve POs',
            },
        ),
        migrations.CreateModel(
            name='ResolvePO_Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(default='', max_length=200)),
                ('transaction_type', models.CharField(default='', max_length=200)),
                ('transaction_date', models.DateField(auto_now_add=True)),
                ('transaction_location', models.CharField(default='', max_length=200)),
                ('item_quantity', models.IntegerField(blank=True, null=True)),
                ('item_number', models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys.Item')),
            ],
            options={
                'verbose_name': 'Resolve PO Transaction',
                'verbose_name_plural': 'Resolve PO Transactions',
            },
        ),
    ]
